### ISSUE TITLE
line 570 fwrite error in cudaica.m 

### ISSUE THREAD

**Issue by mood1111** [yhz-1995/cudaica_win#1]
By googling, the fwrite function doesn't support struct class in windows.

**Comment by CloudyDory** [comment]
Hi, I am sorry for the inconvenience, but I have never encountered this issue. Can you please tell me how you call cudaica.m (including all the input arguments), and what Matlab version are you using?

**Comment by eplab1745** [comment]
Yes, I am getting the same error. Greatly appreciate your work on this. I am using 2018a. I am not certain if there is an MKL error as well.

**Comment by CloudyDory** [comment]
Hi, @eplab1745,

Can you please let me know how you call cudaica? Did you do it via EEGLAB GUI or via command line calling? If you do it from command line, what input argument do you give? There are only two places in cudaica.m that call floatwrite() function(which calls fwrite() on line 570), and right now I can't see how you can let Matlab trying to write a structure to file.

**Comment by mood1111** [comment]
Thanks for reply. It's a very exciting tool if worked under win.
1. My matlab version is 2016b
2. First I call it via EEGLAB, but it seems not working.( monitoring by the GPU tool of CUDA). Then I called it directly, in this method '[wts,sph] = cudaica( datavar)',the error came up. 
3. By debugging mode, as far as I know, the function try to make the entire EEG struct to 'double' precision, by using the fwrite method to write back to the original EEG dataset, then struct unsupported.

**Comment by CloudyDory** [comment]
Hi, @mood1111 

Thanks for the information. Let's get things more clear and solve the problem you met.

1. "I call it via EEGLAB, but it seems not working"
(1). The image below is how I call cudaica from EEGLAB GUI. Is it the same way as you?
![call_cudaica_from_gui](https://user-images.githubusercontent.com/38786521/47191735-993ab600-d37b-11e8-8d31-e713b110a0a7.PNG)

(2). Can you please paste some output from MATLAB after you call cudaica from EEGLAB?

(3). Do you have enough GPU memory?

(4). There is some possibility that cudaica.exe cannot run on your hardware/driver/OS combinations. I have tested it on Windows 10 1803 with NVIDIA 1050Ti, 1080Ti, Windows 7 with NVIDIA 1070, Quadro M2000, and Windows Server 2016 with NVIDIA Quadro M2000. What hardware did you use? If your hardware is not on this list, you may need to recompile the cudaica.exe.

2. "I called it directly, in this method '[wts,sph] = cudaica( datavar)',the error came up"

The cudaica.m function (though not written by me) is intended to be an *internal function* that should be called by the EEGLAB top-level function "pop_runica.m". That's why I provide a modified pop_runica.m (based on EEGLAB 14.1.2) in the "replace" folder. It is, still, possible to call cudaica.m directly (though not recommanded), but you need to do proper data preprocessing that pop_runica.m does, and give cudaica.m proper ICA options. 

In your case, what variable did you assign to "datavar"? It seems to me that you are parsing the entire EEG structure. This is wrong. You should parse EEG.data along, and EEG.data should be converted to double precision and reshape to 2-dimensional matrix if your data is epoched. Read pop_runica.m carefully and you will see how EEG.data is preprocessed before finally throughing it to runica.m, the CPU version of cudaica.m. Also be careful about what ICA options does pop_runica.m use, and you may need to parse the same options if you intend to call cudaica.m directly.

Hope this helps,

Regards,

**Comment by CloudyDory** [comment]
For future reference, this is how I run cudaica from Matlab command line:

`[EEG,command] = pop_runica(EEG, 'icatype', 'cudaica', 'options', {'extended',1,'pca',63}, 'chanind', 1:64);`

If you intend to do it like me, be sure to modify the original EEGLAB pop_runica.m and icadefs.m function so that they recognize cudaica plugin. An example of modified pop_runica.m and icadefs.m is provided in the "replace" folder. They are based on EEGLAB 14.1.2. You can either directly overwrite your original functions, or if you want to be safe, modify these two functions by yourself.

**Comment by mood1111** [comment]
Thanks for the reply.

> 1. "I call it via EEGLAB, but it seems not working"
>    (1). The image below is how I call cudaica from EEGLAB GUI. Is it the same way as you?

Yes, I do the same.
> 
> (2). Can you please paste some output from MATLAB after you call cudaica from EEGLAB?
> (3). Do you have enough GPU memory?

Sorry, I test the program on my other computer, and the code show nothing but directly runs, and there is nothing changed in the CUDA GPU monitor tool window(double checked when the code running).

> (4). There is some possibility that cudaica.exe cannot run on your hardware/driver/OS combinations. I have tested it on Windows 10 1803 with NVIDIA 1050Ti, 1080Ti, Windows 7 with NVIDIA 1070, Quadro M2000, and Windows Server 2016 with NVIDIA Quadro M2000. What hardware did you use? If your hardware is not on this list, you may need to recompile the cudaica.exe.

NVIDIA GF 840m, which have 2GB RAM. My system is WIN7x64. I called the CUDAICA.exe via cmd window, it shows select the card successively.

> 
> 1. "I called it directly, in this method '[wts,sph] = cudaica( datavar)',the error came up"
> 
> The cudaica.m function (though not written by me) is intended to be an _internal function_ that should be called by the EEGLAB top-level function "pop_runica.m". That's why I provide a modified pop_runica.m (based on EEGLAB 14.1.2) in the "replace" folder. It is, still, possible to call cudaica.m directly (though not recommanded), but you need to do proper data preprocessing that pop_runica.m does, and give cudaica.m proper ICA options.
> 
> In your case, what variable did you assign to "datavar"? It seems to me that you are parsing the entire EEG structure. This is wrong. You should parse EEG.data along, and EEG.data should be converted to double precision and reshape to 2-dimensional matrix if your data is epoched. Read pop_runica.m carefully and you will see how EEG.data is preprocessed before finally throughing it to runica.m, the CPU version of cudaica.m. Also be careful about what ICA options does pop_runica.m use, and you may need to parse the same options if you intend to call cudaica.m directly.

Just for testing, I directly called cudaica.m. It seems I was wrong.

**Comment by CloudyDory** [comment]
Hi, thanks for the further information.

1. I forget to mention one known issue: when you call cudaica, be sure that the current directory of MATLAB does not contain any spaces, and I recommend that any non-English or number characters should not be included as well. Otherwise cudaica.exe may fail to read the file saved by cudaica.m, and the program will return nothing.

2. Set a breakpoint at line 333 of cudaica.m. Run cudaica from EEGLAB GUI, did you notice that it creates two files ("cudaica.fdt" and "cudaica.sc"; or "cudaicaXXX.fdt" and "cudaicaXXX.sc", where XXX is some random numbers but should be the same in these two files) in your current folder? If the two files are created, then first half of "cudaica.m" should works fine.

3. Run line 333. This line calls cudaica.exe. Please provide all the Matlab command line output, either copy-and-past, or a screen shot. You mentioned that when you call cudaica.exe from Windows command prompt, it shows it can select GPU device successfully. This output should also shows in Matlab command line. If anything failed at this step, the error information should also be printed out in Matlab command line.

4. If this line runs successfully, then I think your problem should be solved. Run the remaining part of cudaica.m, and see if you get the ICA weights and sphere matrix.

The following part is what the Matlab command line output from a successful run should look like.
```
Attempting to convert data matrix to double precision for more accurate ICA results.
cudaica: using source file 'D:\Users\Admin\Program\MATLAB\Add-Ons\Toolboxes\eeglab14_1_2b\functions\sigprocfunc\binica.sc'
cudaica(): using binary ica file 'D:\Users\Admin\Program\MATLAB\Add-Ons\Toolboxes\eeglab14_1_2b\plugins\CudaICA1.0\cudaica_win.exe'
cudaica(): processing 2 (flag, arg) pairs.
   setting lrate, 0.001
   setting extended, 1
scriptfile = cudaica.sc

cudaica(): ica script file cudaica.sc data D:\Users\Admin\Program\MATLAB\cudaica.fdt pwd D:\Users\Admin\Program\MATLAB.

Running ica from script file cudaica.sc
Starting CUDAICA v1.0 with floating point numbers size = 8 bytes 
===================== 
List of cuda devices: 
===================== 
 
Device: 0 
CUDA Device capabilities: 
	Name: GeForce GTX 1050 Ti 
	Global Mem: 4294967296 
	Mem: 4294967296 
	Mem per Block: 49152 
	Regs per Block: 65536 
	Warp size: 32 
	Mem pitch: 2147483647 
	Max Threads per Block: 1024 
	Max Threads Dim: 1024 x 1024 x 64 
	Max Grid Size: 2147483647 x 65535 x 65535 
	Total Const Mem: 65536 
	Major: 6 
	Minor: 1 
	Clock Rate: 1620000 
	Texture Alignment: 512 
	Device Overlap: 1 
	Multiprocessor Count: 6 
	Kernel Timeout Enabled: 0 
	Integrated: 0 
	Can Map host mem: 1 
	Compute mode: 0 
	Concurrent kernels: 1 
	ECC Enabled: 0 
	PCI Bus ID: 1 
	PCI Device ID: 0 
	TCC Driver: 0 
 
 
Selecting device 0 Success! 
===================== 
 
==================================== 
 Opening config file  
==================================== 
 
==================================== 
          Configuration 
 
	datafile = D:\Users\Admin\Program\MATLAB\cudaica.fdt 
	nchannels = 32 
	nsamples = 30504 
	weightsoutfile = D:\Users\Admin\Program\MATLAB\cudaica.wts 
	sphereoutfile = D:\Users\Admin\Program\MATLAB\cudaica.sph 
	sphering = on 
	biasing = on 
	extblocks = 1 
	pca = 0 
	weightsinfile = (null) 
	lrate = 0.0010000000000000 
	block = 0 
	nochange = 0.0000001000000000 
	maxsteps = 512 
	posact = off 
	annealstep = 0.9800000000000000 
	annealdeg = 60.0000000000000000 
	momentum = 0.0000000000000000 
	nsub = 1 
	pdfsize = 6000 
	urextblocks = 1 
	signsbias = 0.0200000000000000 
	extended = on 
	verbose = 2 
	seed = 1539928080 
	activationsfile = (null) 
	biasfile = (null) 
	signfile = (null) 
==================================== 
 
==================================== 
 Pre processing 
==================================== 
 
Loading dataset...Done! 
Centering dataset...Done! 
Whitening dataset...Done! 
==================================== 
            Dataset info             
                                     
 Channels: 32 
 Samples: 30504 
 Elements: 976128 
 Device pointer: 0000000702A00000 
 Pitch: 512 
 Data: 0000023704549040 
 Sphere pointer: 0000000703A00000 
 Sphere Pitch: 512 
 Weights pointer: 0000000000000000 
 Weights Pitch: 0 
==================================== 
Elapsed pre-processing time = 0 h 0 m 0 s 
==================================== 
 
==================================== 
 Starting Infomax 
==================================== 
 
********************************* 
      Infomax configuration       
********************************* 
  channels 32 
  samples 30504 
  biasing 1 
  extblocks 1 
  lrate 0.0010000000000000 
  block 52 
  nochange 0.0000001000000000 
  maxsteps 512 
  annealstep 0.9800000000000000 
  annealdeg 60.0000000000000000 
  momentum 0.0000000000000000 
  nsub 1 
  pdfsize 6000 
  urextblocks 1 
  signsbias 0.0200000000000000 
  extended 1 
  t 0 
  data 0000000702A00000 
  pitch 512 
********************************* 
Step 1 - lrate 0.001000000, wchange 13.883226010 - time = 0 s 
Step 2 - lrate 0.001000000, wchange 0.445783234 - time = 0 s 
......(multiple lines ignored here)
Step 308 - lrate 0.000002108, wchange 0.000000176, angledelta 99.7 deg - time = 0 s 
Step 309 - lrate 0.000002066, wchange 0.000000086, angledelta 95.2 deg - time = 0 s 
 
Elapsed Infomax ICA time: 0 h 0 m 24 s 

====================================
 Post processing
====================================

Sorting components in descending order of mean projected variance ...
Done post-processing!

Scaling components to RMS microvolt
eeg_checkset: recomputing the ICA activation matrix ...
Done.
````

**Comment by mood1111** [comment]
Cudawin crashed. Maybe due to my x64 system?
![image](https://user-images.githubusercontent.com/44025451/47249197-504e3480-d443-11e8-8bb0-bfd2cfe46770.png)
  应用程序版本:	0.0.0.0
  应用程序时间戳:	5b8f48b0
  故障模块名称:	KERNELBASE.dll
  故障模块版本:	6.1.7601.24094
  故障模块时间戳:	5abee68a
  异常代码:	c06d007e
  异常偏移:	000000000001a06d
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	b697
  其他信息 2:	b697280fbb9bafcc1da14f1340b0e2d7
  其他信息 3:	dd43
  其他信息 4:	dd435e7f7b6f6cc9af2db9fc2524a2e2

**Comment by CloudyDory** [comment]
Hi, It seems that cudaica_win.exe crashed when whitening the data.

Unfortunately right now I don't have a clear suggestion of what is causing this. I don't think it is because your x64 system, because this tool is built for x64 platform, and we have tested it on our own Windows 7 x64 machine and it works fine. 

Maybe you don't have an up-to-dated Windows 7, or an update-to-date software or driver. The faulty component "kernelbase.dll" is a Windows component, but I am not a Windows expert so I can't really trouble-shoot this. You may try re-building this tool from source code with Visual Studio (I use version 15.6.7) and see if it works on your machine, or try Googling on this issue. I did a quick search and it seems that a lot of programs have crashed with kernelbase.dll, and see if some of their solutions works.

Best,

**Comment by mood1111** [comment]
It worked。Great tools，super fast even on my NV 840M card, Thanks.
Finally，I upgrade to Win10。So it's a system problem before。
**Some tips for config：**
1. MKL system path, means“Advanced system settings->Environment Variables->System Variables->Select the 'Path' then add the directory of the MKL lib path and the compiler path". 
2. Set the cudaica_win to run as Administor by r click and select attributes.
3. Run cudaica by script,like'[EEG,command] = pop_runica(EEG, 'icatype', 'cudaica', 'options', {'extended',1,'pca',63}, 'chanind', 1:64);'. I can't call cudaica by pop up window of EEGlab.

**Comment by UgoBruzadin** [comment]
Hi mood1111,
Have you tried double clicking on cudaica on the GUI? It actually runs cudaica for me if I double click it (e.g. if you wanna be sure it's clicked, write something in the options space. Click on 'cudaica', then click again. If it resets it to default, it's clicked!
